include: package:flutter_lints/flutter.yaml

analyzer:

linter:
    rules:
        always_use_package_imports: true
        avoid_empty_else: true
        avoid_returning_null_for_future: true
        avoid_slow_async_io: true
        avoid_type_to_string: true
        cancel_subscriptions: true
        close_sinks: true
        collection_methods_unrelated_type: true
        literal_only_boolean_expressions: true
        no_adjacent_strings_in_list: true
        test_types_in_equals: true
        throw_in_finally: true
        unnecessary_statements: true
        unsafe_html: true
        always_declare_return_types: true
        avoid_bool_literals_in_conditional_expressions: true
        avoid_catching_errors: true
        avoid_escaping_inner_quotes: true
        avoid_multiple_declarations_per_line: true
        avoid_positional_boolean_parameters: true
        avoid_returning_null: true
        avoid_unused_constructor_parameters: true
        avoid_void_async: true
        cast_nullable_to_non_nullable: true
        directives_ordering: true
        join_return_with_assignment: true
        leading_newlines_in_multiline_strings: true
        missing_whitespace_between_adjacent_strings: true
        prefer_double_quotes: true
        prefer_final_in_for_each: true
        prefer_if_elements_to_conditional_expressions: true
        prefer_int_literals: true
        prefer_null_aware_method_calls: true
        require_trailing_commas: true
        slash_for_doc_comments: true
        sort_constructors_first: true
        sort_unnamed_constructors_first: true
        unnecessary_lambdas: true
        unnecessary_null_checks: true
        unnecessary_parenthesis: true
        unnecessary_raw_strings: true
        unnecessary_to_list_in_spreads: true
        use_colored_box: true
        use_decorated_box: true
        use_enums: true
        use_if_null_to_convert_nulls_to_bools: true
        use_is_even_rather_than_modulo: true
        use_named_constants: true
        use_raw_strings: true
        use_string_buffers: true
        use_super_parameters: true
