name: mapplet
description: The easiest way to store map for offline use
version: 1.0.1

platforms:
    android:
    ios:
    linux:
    macos:
    windows:

environment:
    sdk: ">=2.19.4 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_map: ^3.1.0
    http: ^0.13.5
    isar: ^3.0.5
    isar_flutter_libs: ^3.0.5
    latlong2: ^0.8.1
    meta: ^1.8.0
    queue: ^3.1.0+2
    quiver: ^3.2.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
    isar_generator: ^3.0.5
    build_runner: ^2.3.3
